=== mmnaseri/Pongo/schema/strings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.agileapes.com/pongo/strings"
           xmlns="http://www.agileapes.com/pongo/strings"
           elementFormDefault="qualified">

    <xs:element name="strings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="string" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value" type="string"/>
                            <xs:element name="translation" type="string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="language" type="languageCode" use="required"/>
            <xs:attribute name="country" type="countryCode" use="required"/>
            <xs:attribute name="context" type="xs:string" use="optional"/>
            <xs:attribute name="score" type="xs:string" use="optional" default="1"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="languageCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="countryCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="string" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" processContents="skip"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mmnaseri/Pongo/modules/system/test.fa_IR.lang.xml
<?xml version="1.0" encoding="UTF-8"?>
<strings xmlns="http://www.agileapes.com/pongo/strings"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.agileapes.com/pongo/strings ../../schema/strings.xsd" country="IR" language="fa"
         context="general">

    <string>
        <value>Hello world!</value>
        <translation>سلام دنیا!</translation>
    </string>

    <string>
        <value>Link</value>
        <translation>پیوند</translation>
    </string>

    <string>
        <value>Persian</value>
        <translation>پارسی</translation>
    </string>

    <string>
        <value>English</value>
        <translation>انگلیسی</translation>
    </string>

    <string>
        <value>Login</value>
        <translation>ورود</translation>
    </string>

    <string>
        <value>Test</value>
        <translation>آزمایش</translation>
    </string>

    <string>
        <value>Not Found</value>
        <translation>پیدا نشد</translation>
    </string>

    <string>
        <value>Access Denied</value>
        <translation>خطای دست‌رسی</translation>
    </string>

    <string>
        <value>Username:</value>
        <translation>شناسه‌ی کاربری:</translation>
    </string>

    <string>
        <value>Password:</value>
        <translation>گذرواژه:</translation>
    </string>

    <string>
        <value>Password here ...</value>
        <translation>اینجا جای گذرواژه است ...</translation>
    </string>

    <string>
        <value>Invalid username/password</value>
        <translation>شناسه‌ی کاربری و/یا گذرواژه‌ی واردشده صحیح نیست.</translation>
    </string>

</strings>

=== mmnaseri/Pongo/kernel/calendars/jalali.fa_IR.lang.xml
<?xml version="1.0" encoding="UTF-8"?>
<strings xmlns="http://www.agileapes.com/pongo/strings"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.agileapes.com/pongo/strings ../../schema/strings.xsd"
         language="fa" country="IR"
         context="jalali">

    <string>
        <value>Shanbeh</value>
        <translation>شنبه</translation>
    </string>
    <string>
        <value>Yekshanbeh</value>
        <translation>یک‌شنبه</translation>
    </string>
    <string>
        <value>Doshanbeh</value>
        <translation>دوشنبه</translation>
    </string>
    <string>
        <value>Seshanbeh</value>
        <translation>سه‌شنبه</translation>
    </string>
    <string>
        <value>Chaharshanbeh</value>
        <translation>چهارشنبه</translation>
    </string>
    <string>
        <value>Panjshanbeh</value>
        <translation>پنج‌شنبه</translation>
    </string>
    <string>
        <value>Jom'eh</value>
        <translation>جمعه</translation>
    </string>
    <string>
        <value>Farvardin</value>
        <translation>فروردین</translation>
    </string>
    <string>
        <value>Ordibehesht</value>
        <translation>اردی‌بهشت</translation>
    </string>
    <string>
        <value>Khordad</value>
        <translation>خرداد</translation>
    </string>
    <string>
        <value>Tir</value>
        <translation>تیر</translation>
    </string>
    <string>
        <value>Mordad</value>
        <translation>مرداد</translation>
    </string>
    <string>
        <value>Shahrivar</value>
        <translation>شهریور</translation>
    </string>
    <string>
        <value>Mehr</value>
        <translation>مهر</translation>
    </string>
    <string>
        <value>Aban</value>
        <translation>آبان</translation>
    </string>
    <string>
        <value>Azar</value>
        <translation>آذر</translation>
    </string>
    <string>
        <value>Dey</value>
        <translation>دی</translation>
    </string>
    <string>
        <value>Bahman</value>
        <translation>بهمن</translation>
    </string>
    <string>
        <value>Esfand</value>
        <translation>اسفند</translation>
    </string>
    <string>
        <value>st</value>
        <translation>ام</translation>
    </string>
    <string>
        <value>nd</value>
        <translation>ام</translation>
    </string>
    <string>
        <value>rd</value>
        <translation>ام</translation>
    </string>
    <string>
        <value>th</value>
        <translation>ام</translation>
    </string>
    <string>
        <value>IRST</value>
        <translation>زمان رسمی ایران</translation>
    </string>
    <string>
        <value>Rial</value>
        <translation>ریال</translation>
    </string>
    <string>
        <value>Rials</value>
        <translation>ریال</translation>
    </string>
    <string>
        <value>IRR</value>
        <translation>ریال</translation>
    </string>
</strings>
